name: p3p7
channels:
  - diffpy
  - defaults
dependencies:
  - ca-certificates=2022.3.29=hecd8cb5_1
  - certifi=2021.10.8=py37hecd8cb5_2
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - ncurses=6.3=hca72f7f_2
  - openssl=1.1.1n=hca72f7f_0
  - pip=21.2.2=py37hecd8cb5_0
  - python=3.7.13=hdfd78df_0
  - readline=8.1.2=hca72f7f_1
  - setuptools=61.2.0=py37hecd8cb5_0
  - sqlite=3.38.2=h707629a_0
  - tk=8.6.11=h7bc2e8c_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.12=h4dc903c_2
  - pip:
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - ase==3.22.1
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - biopython==1.79
    - bleach==5.0.0
    - bsym==1.2.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - codeclimate-test-reporter==0.2.3
    - coverage==4.3.4
    - cycler==0.11.0
    - cython==0.29.30
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dynesty==1.0.1
    - emcee==3.1.2
    - entrypoints==0.4
    - fastjsonschema==2.15.3
    - fonttools==4.33.2
    - fortranformat==1.2.0
    - future==0.18.2
    - griddataformats==0.7.0
    - gsd==2.6.0
    - icet==2.1
    - idna==3.3
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - ipykernel==6.13.0
    - ipython==7.32.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.1
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.3.0
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - kinisi==0.3.10
    - kiwisolver==1.4.2
    - llvmlite==0.38.0
    - lxml==4.9.0
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mdanalysis==2.1.0
    - mistune==0.8.4
    - mmtf-python==1.1.3
    - monty==2022.3.12
    - mpmath==1.2.1
    - mrcfile==1.4.3
    - msgpack==1.0.4
    - nbclient==0.6.0
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - networkx==2.6.3
    - notebook==6.4.11
    - numba==0.55.1
    - numpy==1.20.3
    - packaging==21.3
    - palettable==3.3.0
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.0
    - plotly==5.7.0
    - polyhedral-analysis==0.1
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - psutil==5.9.0
    - ptitprince==0.2.5
    - ptyprocess==0.7.0
    - pybind11==2.9.2
    - pycparser==2.21
    - pygments==2.12.0
    - pyhamcrest==2.0.3
    - pymatgen==2022.0.17
    - pyparsing==3.0.8
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - requests==2.27.1
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - site-analysis==0.0.2
    - six==1.16.0
    - soupsieve==2.3.2.post1
    - spglib==1.16.3
    - sympy==1.10.1
    - tabulate==0.8.9
    - tenacity==8.0.1
    - terminado==0.13.3
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tornado==6.1
    - tqdm==4.64.0
    - trainstation==1.0
    - traitlets==5.1.1
    - typing-extensions==4.2.0
    - uncertainties==3.1.6
    - uravu==1.2.7
    - urllib3==1.26.9
    - vasppy==0.7.1.0
    - vg==2.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - zipp==3.8.0
prefix: /Users/swc57/miniconda3/envs/p3p7
